#ifndef HAL_H
#define HAL_H

#define I2C_SDA_PIN PC4
#define I2C_SCL_PIN PC5

#define OLED_ADDRESS 0x3C
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 32

#define BUZZER_PIN 9 //PB1
#define KEY0_PIN 3 //PD3
#define KEY1_PIN 4 //PD4
#define KEY2_PIN PE4
#define KEY3_PIN PE5

#define VOLTAGE_SENSOR_PIN PC2

// #define STEP_MOTOR_INT4_PIN PE0
// #define STEP_MOTOR_INT2_PIN PE1
// #define STEP_MOTOR_INT1_PIN PE2
// #define STEP_MOTOR_INT3_PIN PE3

#define STEP_MOTOR_INT1_PIN PE0
#define STEP_MOTOR_INT2_PIN PE1
#define STEP_MOTOR_INT3_PIN PE2
#define STEP_MOTOR_INT4_PIN PE3


#endif // HAL_H
